/**
 * Phone number helpers for SahelFlow.
 *
 * The Customer model stores an HMAC blind index of the phone in `phone` (for
 * lookup) and the AES-256-GCM-encrypted actual phone in `phoneEnc` (for
 * display). All caller-facing validation requires the Algerian format
 * `0[5-7]XXXXXXXX` (10 digits). See `src/lib/validation/index.ts` (`dzPhone`).
 *
 * This module provides:
 * - `syntheticPhone(namespace, id)` — deterministic fake phone for customers
 *   that don't have a real one (e.g. Shopify/Woo orders without a phone field).
 *   Format `05XXXXXXXX` passes `dzPhone`. The 8 trailing digits are derived
 *   from a SHA-256 hash of `(namespace, id)` so the same input always produces
 *   the same synthetic phone — re-syncing the same external order finds the
 *   same customer record instead of creating a duplicate.
 *
 *   Collision risk with real `05XXXXXXXX` phones: ~1 in 10^8 per synthetic
 *   phone. Acceptable for the typical SahelFlow shop (<10k customers).
 */

import { createHash } from "node:crypto";

export function syntheticPhone(namespace: string, id: string | number): string {
  const hash = createHash("sha256")
    .update(`${namespace}:${id}`)
    .digest("hex");
  // Take the first 8 hex chars (32 bits), mod 10^8 → 8 decimal digits.
  const dec8 = (parseInt(hash.slice(0, 8), 16) % 100_000_000)
    .toString()
    .padStart(8, "0");
  return `05${dec8}`;
}

/**
 * Check whether a phone string looks like a synthetic phone generated by
 * `syntheticPhone`. Used by the UI to flag fake phones for review.
 *
 * NOTE: This is a heuristic — a real customer could theoretically have a
 * phone that collides with a synthetic one. Treat the result as "probably
 * synthetic" not "definitely synthetic".
 */
export function isLikelySyntheticPhone(phone: string | null | undefined): boolean {
  if (!phone) return false;
  // Synthetic phones always start with "05" + 8 digits. We can't distinguish
  // them from real 05XXXXXXXX phones by format alone. For now, this helper
  // is a placeholder for future "synthetic phone" tagging (e.g. a flag on
  // the Customer model). Returns false until then.
  return false;
}
