"use client";

import { useState, useTransition } from "react";
import Link from "next/link";
import { ExternalLink, Eye, EyeOff, Loader2, Pencil, Trash2 } from "lucide-react";
import { ConfirmDialog } from "@/components/shared/confirm-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useI18n } from "@/hooks/use-i18n";
import type { StorefrontConfig } from "@/lib/storefront/service";
import { toast } from "@/lib/toast";

export function StorefrontsListClient({ configs: initial, canManage, canPublish }: { configs: StorefrontConfig[]; canManage: boolean; canPublish: boolean }) {
  const { t } = useI18n(); const canMutate = canManage && canPublish; const [configs, setConfigs] = useState(initial); const [, startTransition] = useTransition(); const [toggleId, setToggleId] = useState<string | null>(null); const [deleteTarget, setDeleteTarget] = useState<StorefrontConfig | null>(null);
  async function toggleActive(config: StorefrontConfig) { if (!canMutate || toggleId) return; const newValue = !config.isActive; setToggleId(config.id); try { const res = await fetch(`/api/storefront/config/${config.id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ isActive: newValue }) }); if (!res.ok) { const data = await res.json().catch(() => ({})); throw new Error(data.error || t("storefront.list.error.updateFailed")); } setConfigs((current) => current.map((item) => item.id === config.id ? { ...item, isActive: newValue } : item)); toast.success(newValue ? t("storefront.list.activated") : t("storefront.list.deactivated")); } catch (error) { toast.error(error instanceof Error ? error.message : t("storefront.list.error.generic")); } finally { setToggleId(null); } }
  async function confirmDelete() { if (!deleteTarget) return; const target = deleteTarget; await new Promise<void>((resolve, reject) => { startTransition(async () => { try { const res = await fetch(`/api/storefront/config/${target.id}`, { method: "DELETE" }); if (!res.ok) throw new Error(t("storefront.list.error.deleteFailed")); setConfigs((current) => current.filter((item) => item.id !== target.id)); toast.success(t("storefront.list.deleted")); setDeleteTarget(null); resolve(); } catch (error) { toast.error(error instanceof Error ? error.message : t("storefront.list.error.generic")); reject(error); } }); }); }
  return <><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{configs.map((config) => <Card key={config.id} className="flex flex-col"><CardHeader className="pb-3"><div className="flex items-start justify-between gap-2"><CardTitle className="line-clamp-1 text-base">{config.name}</CardTitle><Badge variant={config.isActive ? "secondary" : "outline"}>{config.isActive ? t("storefront.list.active") : t("storefront.list.inactive")}</Badge></div><p className="font-mono text-xs text-muted-foreground">/storefront/{config.slug}</p></CardHeader><CardContent className="flex flex-1 flex-col gap-3"><p className="text-sm text-muted-foreground">{config.description || t("storefronts.subtitle")}</p><div className="mt-auto flex items-center gap-1.5 pt-2">{canMutate ? <Button asChild size="sm" variant="outline" className="flex-1"><Link href={`/storefronts/${config.id}`}><Pencil className="me-1.5 size-3.5" />{t("storefront.list.edit")}</Link></Button> : null}<Button asChild size="sm" variant="ghost" aria-label={t("storefront.list.publicPreview")}><a href={`/storefront/${config.slug}`} target="_blank" rel="noopener noreferrer"><ExternalLink className="size-3.5" /></a></Button>{canMutate ? <><Button size="sm" variant="ghost" aria-label={config.isActive ? t("storefront.list.deactivate") : t("storefront.list.activate")} disabled={toggleId === config.id} onClick={() => void toggleActive(config)}>{toggleId === config.id ? <Loader2 className="size-3.5 animate-spin" /> : config.isActive ? <EyeOff className="size-3.5" /> : <Eye className="size-3.5" />}</Button><Button size="sm" variant="ghost" className="text-destructive" aria-label={t("storefront.list.delete")} onClick={() => setDeleteTarget(config)}><Trash2 className="size-3.5" /></Button></> : null}</div></CardContent></Card>)}</div><ConfirmDialog open={canMutate && deleteTarget !== null} onOpenChange={(open) => !open && setDeleteTarget(null)} title={t("storefront.list.deleteTitle")} description={t("storefront.list.deleteConfirm", { name: deleteTarget?.name ?? "" })} confirmLabel={t("storefront.list.confirmDelete")} destructive onConfirm={confirmDelete} /></>;
}
