// Every visible word of sahelflow.com, in the three SahelFlow languages.
// Arabic is the default locale. Claims stay inside what the product does.

const ar = {
  dir: "rtl",
  lang: "ar",
  name: "العربية",
  meta: {
    title: "SahelFlow — نظام تشغيل تجارة الدفع عند الاستلام في الجزائر",
    description:
      "SahelFlow يجمع طلباتك، واتساب، التوصيل، المرتجعات والمحاسبة في تطبيق واحد على حاسوبك. مصمَّم للتجار الجزائريين الذين يبيعون بالدفع عند الاستلام.",
  },
  nav: {
    features: "المزايا",
    how: "كيف يعمل",
    integrations: "التكاملات",
    security: "الأمان",
    faq: "الأسئلة",
    download: "تحميل",
    trial: "جرّب مجاناً",
    menu: "القائمة",
    language: "اللغة",
  },
  hero: {
    eyebrow: "مصمَّم لتجارة الدفع عند الاستلام في الجزائر",
    title: ["بِع أكثر. استرجع أقل.", "واعرف مصير كل دينار."],
    lead:
      "SahelFlow نظام تشغيل تجارة الدفع عند الاستلام: طلبات واتساب يلتقطها الذكاء الاصطناعي، تأكيدات مرتّبة حسب المخاطر، شركات توصيل متزامنة، ومال مُطابَق حتى آخر دينار — على حاسوبك، وحتى دون إنترنت.",
    primary: "ابدأ مجاناً — 7 أيام",
    secondary: "تحدّث مع إنسان على واتساب",
    note: (days) => `${days} أيام مجاناً · Windows 10 و 11 · بدون بطاقة بنكية`,
    trust: ["يعمل حتى بدون إنترنت", "عربية · Français · English", "بياناتك تبقى على حاسوبك"],
  },
  strip: "يعمل مع الأدوات التي تستعملها يومياً",
  problem: {
    eyebrow: "المشكلة",
    title: "متجرك يعمل اليوم على واتساب، وثلاث لوحات توصيل، ودفتر، وذاكرتك. هناك يتسرّب ربحك.",
    items: [
      { title: "طلبات ضائعة في واتساب", text: "زبون يرسل الاسم والولاية والهاتف في ثلاث رسائل، وأنت تنسخها يدوياً في جدول." },
      { title: "مرتجعات تأكل الربح", text: "طرد يعود يعني مصاريف توصيل ضائعة وسلعة مجمَّدة، ولا أحد يقول لك من أين تأتي الخسارة." },
      { title: "مال لا تعرف أين هو", text: "شركات التوصيل تحصّل، تقتطع رسومها، وتحوّل لاحقاً. المطابقة تتم في دفتر أو لا تتم أبداً." },
    ],
  },
  features: {
    eyebrow: "المنصة",
    title: "كل ما يحتاجه متجرك، في مكان واحد.",
    lead: "وحدات مترابطة تشارك نفس الطلب، نفس الزبون ونفس المخزون — فلا شيء يُكتب مرتين.",
    items: [
      {
        key: "orders",
        title: "الطلبات وطابور التأكيد",
        text: "كل طلب يمر بمسار واضح: جديد، مؤكَّد، مُجهَّز، مشحون، مُسلَّم. طابور التأكيد يرتّب لك من تتصل به أولاً، والمخزون يُحجز ويُحرَّر تلقائياً.",
        points: ["حجز المخزون عند التأكيد", "سجلّ كامل لكل تغيير", "بحث فوري في كل شيء"],
      },
      {
        key: "inbox",
        title: "صندوق واتساب مع ذكاء اصطناعي",
        text: "كل محادثات واتساب في صندوق واحد مع فريقك. اختر رسالة أو عدة رسائل، والذكاء الاصطناعي يستخرج الطلب جاهزاً للمراجعة — الاسم، الهاتف، الولاية، المنتجات.",
        points: ["استخراج الطلب من عدة رسائل", "صور، فيديو، ملفات ورسائل صوتية", "توزيع المحادثات على الفريق"],
      },
      {
        key: "delivery",
        title: "التوصيل مع شركات الجزائر",
        text: "أنشئ الشحنة وتابعها مع Yalidine و ZR Express و EcoTrack و Maystro دون مغادرة التطبيق. أسعار التوصيل حسب الولاية — الـ 58 ولاية، للمنزل وللمكتب.",
        points: ["تتبع الحالة تلقائياً", "58 ولاية · منزل ومكتب", "تصدير قوائم الشحن"],
      },
      {
        key: "risk",
        title: "محرك المخاطر والمرتجعات",
        text: "قبل أن تشحن، SahelFlow يقول لك أي الطلبات تستحق مكالمة تأكيد إضافية، ولماذا. واكتشف أين تخسر فعلاً: حسب الولاية، المنتج والقناة.",
        points: ["قائمة \"تحقّق قبل الشحن\"", "خسائر المرتجعات بالدينار", "قائمة سوداء للزبائن الرافضين"],
      },
      {
        key: "storefront",
        title: "متجرك الإلكتروني في دقائق",
        text: "أنشئ متجراً جميلاً بالعربية أو الفرنسية في أربع خطوات، مع معاينة حية على الهاتف والحاسوب. الطلبات تصل مباشرة إلى SahelFlow.",
        points: ["ثلاثة قوالب احترافية", "صفحات هبوط للمنتجات", "حماية من الطلبات الوهمية"],
      },
      {
        key: "automations",
        title: "أتمتة تعمل وأنت نائم",
        text: "\"إذا وصل طلب جديد، أرسل رسالة تأكيد بعد 10 دقائق، وإذا لم يرد الزبون ذكّرني.\" ابنِ مساراتك بالسحب والإفلات أو انطلق من قالب جاهز.",
        points: ["قوالب جاهزة للتاجر الجزائري", "انتظار وإعادة تحقق قبل كل خطوة", "سجل تشغيل واضح"],
      },
      {
        key: "accounting",
        title: "المحاسبة ومطابقة الدفع عند الاستلام",
        text: "اعرف كم حصّلت شركة التوصيل، كم اقتطعت، وكم يجب أن يصلك. الأرباح الحقيقية بعد التوصيل والمرتجعات، لا أرقام تقريبية.",
        points: ["مطابقة التحويلات", "تكلفة ورسوم كل طرد", "تقارير قابلة للتصدير"],
      },
      {
        key: "agents",
        title: "مساعد ذكي يفهم متجرك",
        text: "اسأل: \"ما المنتجات التي توشك على النفاد؟\" أو \"ألغِ الطلب ORD-0003\". المساعد يعمل على بياناتك الحقيقية، وكل تغيير حساس ينتظر موافقتك.",
        points: ["إجابات من بياناتك الفعلية", "لا تغيير بدون موافقتك", "يدعم الصور ولقطات الشاشة"],
      },
    ],
  },
  how: {
    eyebrow: "كيف يعمل",
    title: "شغّال في اليوم نفسه.",
    steps: [
      { title: "حمّل وثبّت", text: "ثبّت SahelFlow على Windows في دقيقتين وأنشئ رمزك السري." },
      { title: "اربط أدواتك", text: "امسح رمز واتساب، أضف شركة التوصيل ومنتجاتك — أو استورد من Excel أو Shopify أو YouCan." },
      { title: "بِع وراقب", text: "الطلبات تصل، تُؤكَّد، تُشحن وتُطابَق. وأنت ترى كل شيء من لوحة واحدة." },
    ],
  },
  algeria: {
    eyebrow: "صُنع للجزائر",
    title: "ليس برنامجاً أجنبياً مُترجَماً.",
    items: [
      { title: "58 ولاية", text: "أسعار وتوصيل وتحليلات حسب الولاية والبلدية." },
      { title: "الدينار الجزائري", text: "كل الأرقام بالدينار، كما تحسبها أنت." },
      { title: "عربية كاملة", text: "واجهة من اليمين إلى اليسار، وفهم للدارجة في الرسائل." },
      { title: "دفع محلي", text: "ادفع عبر BaridiMob أو CCP." },
    ],
  },
  security: {
    eyebrow: "الأمان والملكية",
    title: "بياناتك تعيش على حاسوبك.",
    lead:
      "مشفّرة بـ AES-256، تعمل دون إنترنت، وملكك وحدك. SahelFlow يحفظ قاعدة بيانات متجرك على جهازك أنت، لا على خادم شخص آخر.",
    items: [
      { title: "تشفير AES-256-GCM", text: "أرقام الهواتف والعناوين والمحادثات مشفّرة على القرص." },
      { title: "يعمل بدون إنترنت", text: "واصل البيع والتأكيد والمحاسبة حتى عند انقطاع الشبكة." },
      { title: "نسخ احتياطي واسترجاع", text: "نسخ احتياطية مشفّرة واسترجاع آمن عند تغيير الحاسوب." },
      { title: "فريق بصلاحيات", text: "أضف موظفيك، وحدّد ما يراه ويفعله كل واحد منهم." },
    ],
  },
  trial: {
    title: "ابدأ تجربتك المجانية اليوم.",
    text: (days) => `${days} أيام كاملة، كل المزايا، بدون بطاقة بنكية. وإن احتجت مساعدة في البداية، نحن على واتساب.`,
    primary: "حمّل SahelFlow",
    secondary: "اسألنا على واتساب",
  },
  faq: {
    eyebrow: "أسئلة شائعة",
    title: "كل ما تريد معرفته.",
    items: [
      { q: "هل أحتاج إنترنت دائماً؟", a: "لا. SahelFlow يعمل على حاسوبك. الإنترنت يُستعمل فقط لواتساب، شركات التوصيل، المتجر الإلكتروني والتفعيل." },
      { q: "على أي نظام يعمل؟", a: "Windows 10 و Windows 11 (64-bit). يُنصح بـ 8 جيغابايت من الذاكرة." },
      { q: "كيف تعمل التجربة المجانية؟", a: (days) => `حمّل التطبيق وفعّل التجربة: ${days} أيام بكل المزايا. بعدها تشترك وتحتفظ بكل بياناتك.` },
      { q: "كيف أشتري الترخيص؟", a: "ادفع عبر BaridiMob أو CCP، أرسل لنا رمز طلب الترخيص من التطبيق على واتساب، ثم الصق الترخيص الذي يصلك. دفعة واحدة، والبرنامج لك." },
      { q: "هل يمكن لعدة موظفين العمل معاً؟", a: "نعم. أضف أعضاء الفريق بصلاحيات مختلفة: تأكيد، شحن، محاسبة أو إدارة كاملة." },
      { q: "هل تُفقد بياناتي إذا انتهت التجربة؟", a: "لا. بياناتك تبقى على حاسوبك ومحفوظة، وتفعيل الترخيص يعيد فتح كل شيء كما تركته." },
      { q: "هل يفهم الذكاء الاصطناعي الدارجة؟", a: "نعم، استخراج الطلبات مصمَّم لرسائل التجار الجزائريين: دارجة، فرنسية وعربية، وحتى خليط منها." },
      { q: "هل يمكنني استيراد طلباتي القديمة؟", a: "نعم، من ملفات Excel/CSV، ومن متاجر Shopify و YouCan و WooCommerce." },
    ],
  },
  download: {
    title: "حمّل SahelFlow لـ Windows",
    lead: "مثبّت موقَّع رقمياً، يُحدِّث نفسه تلقائياً.",
    button: "تحميل المثبّت (Windows)",
    requirementsTitle: "متطلبات النظام",
    requirements: ["Windows 10 أو 11 (نظام 64 بت)", "4 جيغابايت ذاكرة (8 جيغابايت مُستحسَن)", "1 جيغابايت مساحة فارغة", "اتصال إنترنت للتفعيل وواتساب"],
    stepsTitle: "التثبيت في ثلاث خطوات",
    steps: ["افتح ملف المثبّت واتبع الخطوات.", "أنشئ رمزك السري وفعّل التجربة المجانية.", "اربط واتساب وشركة التوصيل — وابدأ."],
    help: "تحتاج مساعدة في التثبيت؟",
  },
  footer: {
    tagline: "نظام تشغيل تجارة الدفع عند الاستلام في الجزائر.",
    product: "المنتج",
    company: "الشركة",
    legal: "قانوني",
    contact: "تواصل",
    privacy: "سياسة الخصوصية",
    terms: "شروط الاستخدام",
    rights: "جميع الحقوق محفوظة.",
  },
  legal: {
    privacyTitle: "سياسة الخصوصية",
    termsTitle: "شروط الاستخدام",
    updated: "آخر تحديث",
  },
  notFound: { title: "الصفحة غير موجودة", text: "ربما نُقلت هذه الصفحة. عُد إلى الصفحة الرئيسية.", back: "الصفحة الرئيسية" },
  whatsappMessage: "السلام عليكم، أريد معرفة المزيد عن SahelFlow",
};

const fr = {
  dir: "ltr",
  lang: "fr",
  name: "Français",
  meta: {
    title: "SahelFlow — Le système d'exploitation du e-commerce COD en Algérie",
    description:
      "SahelFlow réunit vos commandes, WhatsApp, la livraison, les retours et la comptabilité dans une seule application sur votre PC. Conçu pour les vendeurs algériens en paiement à la livraison.",
  },
  nav: {
    features: "Fonctionnalités",
    how: "Comment ça marche",
    integrations: "Intégrations",
    security: "Sécurité",
    faq: "FAQ",
    download: "Télécharger",
    trial: "Essai gratuit",
    menu: "Menu",
    language: "Langue",
  },
  hero: {
    eyebrow: "Conçu pour le paiement à la livraison en Algérie",
    title: ["Vendez plus. Retournez moins.", "Maîtrisez chaque dinar."],
    lead:
      "SahelFlow est le système d'exploitation du e-commerce COD : commandes WhatsApp captées par l'IA, confirmations priorisées par le risque, livreurs synchronisés et encaissements rapprochés au dinar près — sur votre PC, même hors ligne.",
    primary: "Commencer gratuitement — 7 jours",
    secondary: "Parler à un humain sur WhatsApp",
    note: (days) => `${days} jours gratuits · Windows 10 et 11 · sans carte bancaire`,
    trust: ["Fonctionne hors ligne", "العربية · Français · English", "Vos données restent sur votre PC"],
  },
  strip: "Fonctionne avec les outils que vous utilisez chaque jour",
  problem: {
    eyebrow: "Le problème",
    title: "Aujourd'hui, votre boutique tourne sur WhatsApp, trois tableaux de livreurs, un cahier et votre mémoire. C'est là que fuit votre marge.",
    items: [
      { title: "Des commandes perdues dans WhatsApp", text: "Un client envoie nom, wilaya et téléphone en trois messages, et vous recopiez tout à la main." },
      { title: "Des retours qui mangent la marge", text: "Un colis qui revient, ce sont des frais perdus et du stock bloqué — sans savoir d'où vient la perte." },
      { title: "De l'argent qu'on ne voit pas", text: "Les livreurs encaissent, prélèvent leurs frais et versent plus tard. Le rapprochement se fait sur un cahier, ou jamais." },
    ],
  },
  features: {
    eyebrow: "La plateforme",
    title: "Tout ce dont votre boutique a besoin, au même endroit.",
    lead: "Des modules connectés qui partagent la même commande, le même client et le même stock — rien n'est saisi deux fois.",
    items: [
      {
        key: "orders",
        title: "Commandes et file de confirmation",
        text: "Chaque commande suit un parcours clair : nouvelle, confirmée, préparée, expédiée, livrée. La file de confirmation vous dit qui appeler en premier, et le stock se réserve et se libère tout seul.",
        points: ["Réservation du stock à la confirmation", "Historique complet de chaque changement", "Recherche instantanée partout"],
      },
      {
        key: "inbox",
        title: "Boîte WhatsApp avec IA",
        text: "Toutes vos conversations WhatsApp dans une seule boîte partagée avec l'équipe. Sélectionnez un ou plusieurs messages : l'IA extrait la commande prête à vérifier — nom, téléphone, wilaya, produits.",
        points: ["Extraction depuis plusieurs messages", "Photos, vidéos, documents et vocaux", "Attribution des conversations à l'équipe"],
      },
      {
        key: "delivery",
        title: "Livraison avec les transporteurs algériens",
        text: "Créez et suivez vos expéditions avec Yalidine, ZR Express, EcoTrack et Maystro sans quitter l'application. Tarifs par wilaya — les 58, à domicile et au bureau.",
        points: ["Suivi automatique des statuts", "58 wilayas · domicile et bureau", "Export des bordereaux"],
      },
      {
        key: "risk",
        title: "Moteur de risque et retours",
        text: "Avant d'expédier, SahelFlow vous indique quelles commandes méritent un appel de plus, et pourquoi. Et découvrez où vous perdez vraiment : par wilaya, par produit, par canal.",
        points: ["Liste « à vérifier avant l'envoi »", "Pertes de retours en dinars", "Liste noire des refus répétés"],
      },
      {
        key: "storefront",
        title: "Votre boutique en ligne en quelques minutes",
        text: "Créez une boutique élégante en arabe ou en français en quatre étapes, avec aperçu en direct mobile et ordinateur. Les commandes arrivent directement dans SahelFlow.",
        points: ["Trois modèles professionnels", "Pages produit dédiées", "Protection contre les fausses commandes"],
      },
      {
        key: "automations",
        title: "Des automatisations qui travaillent pour vous",
        text: "« Si une nouvelle commande arrive, envoie un message de confirmation après 10 minutes, et rappelle-moi si le client ne répond pas. » Construisez vos scénarios en glisser-déposer ou partez d'un modèle.",
        points: ["Modèles pensés pour l'Algérie", "Attente et revérification avant chaque étape", "Historique d'exécution clair"],
      },
      {
        key: "accounting",
        title: "Comptabilité et rapprochement COD",
        text: "Sachez combien le livreur a encaissé, combien il a retenu, et combien doit vous revenir. Le vrai bénéfice après livraison et retours, pas une estimation.",
        points: ["Rapprochement des versements", "Coût et frais de chaque colis", "Rapports exportables"],
      },
      {
        key: "agents",
        title: "Un assistant IA qui connaît votre boutique",
        text: "Demandez : « Quels produits sont presque épuisés ? » ou « Annule la commande ORD-0003 ». L'assistant travaille sur vos vraies données, et chaque action sensible attend votre accord.",
        points: ["Réponses tirées de vos données", "Aucun changement sans votre accord", "Comprend les images et captures"],
      },
    ],
  },
  how: {
    eyebrow: "Comment ça marche",
    title: "Opérationnel le jour même.",
    steps: [
      { title: "Téléchargez et installez", text: "Installez SahelFlow sur Windows en deux minutes et créez votre code PIN." },
      { title: "Connectez vos outils", text: "Scannez le QR WhatsApp, ajoutez votre transporteur et vos produits — ou importez depuis Excel, Shopify ou YouCan." },
      { title: "Vendez et pilotez", text: "Les commandes arrivent, sont confirmées, expédiées et rapprochées. Vous voyez tout depuis un seul tableau de bord." },
    ],
  },
  algeria: {
    eyebrow: "Fait pour l'Algérie",
    title: "Pas un logiciel étranger traduit.",
    items: [
      { title: "58 wilayas", text: "Tarifs, livraison et analyses par wilaya et commune." },
      { title: "Dinar algérien", text: "Tous les montants en DA, comme vous les comptez." },
      { title: "Arabe complet", text: "Interface de droite à gauche, et la darija comprise dans les messages." },
      { title: "Paiement local", text: "Abonnement par BaridiMob ou CCP." },
    ],
  },
  security: {
    eyebrow: "Sécurité et propriété",
    title: "Vos données vivent sur votre PC.",
    lead: "Chiffrées en AES-256, disponibles hors ligne, et à vous seul. SahelFlow garde la base de données de votre boutique sur votre machine, pas sur le serveur de quelqu'un d'autre.",
    items: [
      { title: "Chiffrement AES-256-GCM", text: "Téléphones, adresses et conversations sont chiffrés sur le disque." },
      { title: "Fonctionne hors ligne", text: "Continuez à vendre, confirmer et compter même sans réseau." },
      { title: "Sauvegarde et restauration", text: "Sauvegardes chiffrées et restauration sûre en cas de changement de PC." },
      { title: "Équipe avec permissions", text: "Ajoutez vos employés et décidez ce que chacun voit et fait." },
    ],
  },
  trial: {
    title: "Commencez votre essai gratuit aujourd'hui.",
    text: (days) => `${days} jours complets, toutes les fonctionnalités, sans carte bancaire. Besoin d'aide pour démarrer ? On est sur WhatsApp.`,
    primary: "Télécharger SahelFlow",
    secondary: "Nous écrire sur WhatsApp",
  },
  faq: {
    eyebrow: "Questions fréquentes",
    title: "Tout ce que vous voulez savoir.",
    items: [
      { q: "Faut-il une connexion internet en permanence ?", a: "Non. SahelFlow fonctionne sur votre PC. Internet sert uniquement à WhatsApp, aux transporteurs, à la boutique en ligne et à l'activation." },
      { q: "Sur quel système fonctionne-t-il ?", a: "Windows 10 et Windows 11 (64 bits). 8 Go de mémoire recommandés." },
      { q: "Comment fonctionne l'essai gratuit ?", a: (days) => `Téléchargez l'application et activez l'essai : ${days} jours avec toutes les fonctionnalités. Ensuite vous vous abonnez et gardez toutes vos données.` },
      { q: "Comment acheter la licence ?", a: "Payez par BaridiMob ou CCP, envoyez-nous sur WhatsApp le code de demande de licence affiché dans l'app, puis collez la licence reçue. Un seul paiement, et c'est à vous." },
      { q: "Plusieurs employés peuvent-ils travailler ensemble ?", a: "Oui. Ajoutez des membres avec des rôles différents : confirmation, expédition, comptabilité ou gestion complète." },
      { q: "Est-ce que je perds mes données à la fin de l'essai ?", a: "Non. Vos données restent sur votre PC, préservées. Activer une licence rouvre tout exactement comme vous l'avez laissé." },
      { q: "L'IA comprend-elle la darija ?", a: "Oui, l'extraction de commandes est pensée pour les messages des vendeurs algériens : darija, français, arabe, et même un mélange des trois." },
      { q: "Puis-je importer mes anciennes commandes ?", a: "Oui, depuis Excel/CSV, et depuis les boutiques Shopify, YouCan et WooCommerce." },
    ],
  },
  download: {
    title: "Télécharger SahelFlow pour Windows",
    lead: "Un installateur signé, qui se met à jour tout seul.",
    button: "Télécharger l'installateur (Windows)",
    requirementsTitle: "Configuration requise",
    requirements: ["Windows 10 ou 11 · 64 bits", "4 Go de mémoire (8 Go recommandés)", "1 Go d'espace libre", "Connexion internet pour l'activation et WhatsApp"],
    stepsTitle: "Installation en trois étapes",
    steps: ["Ouvrez l'installateur et suivez les étapes.", "Créez votre code PIN et activez l'essai gratuit.", "Connectez WhatsApp et votre transporteur — c'est parti."],
    help: "Besoin d'aide pour l'installation ?",
  },
  footer: {
    tagline: "Le système d'exploitation du paiement à la livraison en Algérie.",
    product: "Produit",
    company: "Entreprise",
    legal: "Légal",
    contact: "Contact",
    privacy: "Politique de confidentialité",
    terms: "Conditions d'utilisation",
    rights: "Tous droits réservés.",
  },
  legal: { privacyTitle: "Politique de confidentialité", termsTitle: "Conditions d'utilisation", updated: "Dernière mise à jour" },
  notFound: { title: "Page introuvable", text: "Cette page a peut-être été déplacée. Revenez à l'accueil.", back: "Accueil" },
  whatsappMessage: "Bonjour, je voudrais en savoir plus sur SahelFlow",
};

const en = {
  dir: "ltr",
  lang: "en",
  name: "English",
  meta: {
    title: "SahelFlow — The operating system for COD commerce in Algeria",
    description:
      "SahelFlow brings your orders, WhatsApp, delivery, returns and accounting together in one app on your PC. Built for Algerian cash-on-delivery sellers.",
  },
  nav: {
    features: "Features",
    how: "How it works",
    integrations: "Integrations",
    security: "Security",
    faq: "FAQ",
    download: "Download",
    trial: "Free trial",
    menu: "Menu",
    language: "Language",
  },
  hero: {
    eyebrow: "Built for cash-on-delivery commerce in Algeria",
    title: ["Sell more. Return less.", "Know every dinar."],
    lead:
      "SahelFlow is the operating system for cash-on-delivery commerce: WhatsApp orders captured by AI, confirmations ranked by risk, couriers in sync and cash reconciled to the last dinar — on your PC, even offline.",
    primary: "Start free — 7 days",
    secondary: "Talk to a human on WhatsApp",
    note: (days) => `${days}-day free trial · Windows 10 and 11 · no card needed`,
    trust: ["Works offline", "العربية · Français · English", "Your data stays on your PC"],
  },
  strip: "Works with the tools you already use every day",
  problem: {
    eyebrow: "The problem",
    title: "Today your shop runs on WhatsApp, three courier dashboards, a notebook and your memory. That's where your margin leaks.",
    items: [
      { title: "Orders lost in WhatsApp", text: "A customer sends their name, wilaya and phone across three messages, and you copy it all by hand." },
      { title: "Returns that eat the margin", text: "Every parcel that comes back is lost delivery fees and frozen stock — and nobody tells you where the loss comes from." },
      { title: "Money you can't see", text: "Couriers collect, take their fees and pay out later. Reconciliation happens in a notebook, or never." },
    ],
  },
  features: {
    eyebrow: "The platform",
    title: "Everything your shop needs, in one place.",
    lead: "Connected modules that share the same order, customer and stock — nothing is typed twice.",
    items: [
      {
        key: "orders",
        title: "Orders and the confirmation queue",
        text: "Every order follows a clear path: new, confirmed, packed, shipped, delivered. The confirmation queue tells you who to call first, and stock is reserved and released automatically.",
        points: ["Stock reserved on confirmation", "Full history of every change", "Instant search across everything"],
      },
      {
        key: "inbox",
        title: "WhatsApp inbox with AI",
        text: "All your WhatsApp conversations in one inbox shared with your team. Select one or more messages and AI extracts the order ready for review — name, phone, wilaya, products.",
        points: ["Extract from several messages", "Photos, videos, documents and voice notes", "Assign conversations to your team"],
      },
      {
        key: "delivery",
        title: "Delivery with Algerian couriers",
        text: "Create and track shipments with Yalidine, ZR Express, EcoTrack and Maystro without leaving the app. Delivery prices per wilaya — all 58, home and desk.",
        points: ["Automatic status tracking", "58 wilayas · home and desk", "Export shipping lists"],
      },
      {
        key: "risk",
        title: "Risk engine and returns",
        text: "Before you ship, SahelFlow tells you which orders deserve an extra confirmation call, and why. And see where you really lose money: by wilaya, product and channel.",
        points: ["A \"check before shipping\" list", "Return losses in dinars", "Blacklist for repeat refusers"],
      },
      {
        key: "storefront",
        title: "Your online store in minutes",
        text: "Create a beautiful store in Arabic or French in four steps, with a live phone and desktop preview. Orders land straight in SahelFlow.",
        points: ["Three professional templates", "Dedicated product landing pages", "Protection against fake orders"],
      },
      {
        key: "automations",
        title: "Automations that work while you sleep",
        text: "\"When a new order arrives, send a confirmation message after 10 minutes, and remind me if the customer doesn't reply.\" Build flows visually or start from a template.",
        points: ["Templates made for Algerian sellers", "Wait and re-check before every step", "Clear run history"],
      },
      {
        key: "accounting",
        title: "Accounting and COD reconciliation",
        text: "Know how much the courier collected, how much they kept and how much is owed to you. Real profit after delivery and returns — not an estimate.",
        points: ["Payout reconciliation", "Cost and fees per parcel", "Exportable reports"],
      },
      {
        key: "agents",
        title: "An AI assistant that knows your shop",
        text: "Ask \"Which products are running low?\" or \"Cancel order ORD-0003\". The assistant works on your real data, and every sensitive change waits for your approval.",
        points: ["Answers from your actual data", "No change without your approval", "Understands images and screenshots"],
      },
    ],
  },
  how: {
    eyebrow: "How it works",
    title: "Up and running the same day.",
    steps: [
      { title: "Download and install", text: "Install SahelFlow on Windows in two minutes and create your PIN." },
      { title: "Connect your tools", text: "Scan the WhatsApp QR code, add your courier and products — or import from Excel, Shopify or YouCan." },
      { title: "Sell and stay in control", text: "Orders arrive, get confirmed, shipped and reconciled. You see everything from one dashboard." },
    ],
  },
  algeria: {
    eyebrow: "Made for Algeria",
    title: "Not a foreign tool with a translation.",
    items: [
      { title: "58 wilayas", text: "Prices, delivery and analytics by wilaya and commune." },
      { title: "Algerian dinar", text: "Every amount in DZD, the way you count it." },
      { title: "Full Arabic", text: "A right-to-left interface, and Darija understood in messages." },
      { title: "Local payment", text: "Subscribe with BaridiMob or CCP." },
    ],
  },
  security: {
    eyebrow: "Security and ownership",
    title: "Your data lives on your PC.",
    lead: "AES-256 encrypted, ready to work offline, and yours alone. SahelFlow keeps your shop's database on your machine, not on someone else's server.",
    items: [
      { title: "AES-256-GCM encryption", text: "Phone numbers, addresses and conversations are encrypted on disk." },
      { title: "Works offline", text: "Keep selling, confirming and counting even when the network drops." },
      { title: "Backup and restore", text: "Encrypted backups and safe restore when you change computers." },
      { title: "Team permissions", text: "Add your staff and decide what each person can see and do." },
    ],
  },
  trial: {
    title: "Start your free trial today.",
    text: (days) => `${days} full days, every feature, no card needed. Need a hand getting started? We're on WhatsApp.`,
    primary: "Download SahelFlow",
    secondary: "Message us on WhatsApp",
  },
  faq: {
    eyebrow: "FAQ",
    title: "Everything you want to know.",
    items: [
      { q: "Do I need internet all the time?", a: "No. SahelFlow runs on your PC. Internet is only used for WhatsApp, couriers, your online store and activation." },
      { q: "Which systems does it run on?", a: "Windows 10 and Windows 11 (64-bit). 8 GB of memory recommended." },
      { q: "How does the free trial work?", a: (days) => `Download the app and start the trial: ${days} days with every feature. Then subscribe and keep all your data.` },
      { q: "How do I buy a licence?", a: "Pay with BaridiMob or CCP, send us the licence request code shown in the app on WhatsApp, then paste the licence you receive. One payment, and it's yours." },
      { q: "Can several employees work together?", a: "Yes. Add team members with different roles: confirmation, shipping, accounting or full management." },
      { q: "Do I lose my data when the trial ends?", a: "No. Your data stays on your PC, preserved. Activating a licence reopens everything exactly as you left it." },
      { q: "Does the AI understand Darija?", a: "Yes. Order extraction is built for Algerian sellers' messages: Darija, French, Arabic — even a mix of all three." },
      { q: "Can I import my existing orders?", a: "Yes, from Excel/CSV files and from Shopify, YouCan and WooCommerce stores." },
    ],
  },
  download: {
    title: "Download SahelFlow for Windows",
    lead: "A signed installer that keeps itself up to date.",
    button: "Download the installer (Windows)",
    requirementsTitle: "System requirements",
    requirements: ["Windows 10 or 11 · 64-bit", "4 GB memory (8 GB recommended)", "1 GB free disk space", "Internet connection for activation and WhatsApp"],
    stepsTitle: "Install in three steps",
    steps: ["Open the installer and follow the steps.", "Create your PIN and start the free trial.", "Connect WhatsApp and your courier — you're live."],
    help: "Need help installing?",
  },
  footer: {
    tagline: "The operating system for cash-on-delivery commerce in Algeria.",
    product: "Product",
    company: "Company",
    legal: "Legal",
    contact: "Contact",
    privacy: "Privacy policy",
    terms: "Terms of use",
    rights: "All rights reserved.",
  },
  legal: { privacyTitle: "Privacy policy", termsTitle: "Terms of use", updated: "Last updated" },
  notFound: { title: "Page not found", text: "This page may have moved. Head back home.", back: "Home" },
  whatsappMessage: "Hello, I'd like to know more about SahelFlow",
};

export const CONTENT = { ar, fr, en };

// Brands the product integrates with (logos are rendered as wordmarks).
export const INTEGRATIONS = [
  "WhatsApp", "Yalidine", "ZR Express", "EcoTrack", "Maystro",
  "Shopify", "YouCan", "WooCommerce", "Google Sheets", "Meta Pixel", "Google Gemini", "Excel / CSV",
];
