// Copy for the navigation and the inner pages (Product, Integrations, Pricing,
// Security). Same rule as content.mjs: every claim stays inside what SahelFlow
// does today. Prices are never invented: SITE.licencePrice decides whether a
// figure or "ask us" is shown.

const en = {
  nav: {
    product: "Product",
    integrations: "Integrations",
    security: "Security",
    pricing: "Pricing",
    faq: "FAQ",
    talk: "Talk to us",
    start: "Start free",
    allFeatures: "See every feature",
    newBadge: "New",
    spotlightTitle: "Google Sheets sync",
    spotlightText: "Orders from your landing-page sheet arrive on their own — and each row shows its live status.",
    close: "Close menu",
  },
  modules: {
    orders: "Confirmation queue that tells you who to call first",
    inbox: "Every WhatsApp chat in one team inbox, orders extracted by AI",
    delivery: "Yalidine, ZR Express, EcoTrack, Maystro — ship and track",
    risk: "Know which order will come back before you ship it",
    storefront: "A store in four steps; orders land in SahelFlow",
    automations: "Messages and reminders that run while you sleep",
    accounting: "What the courier collected, kept and owes you",
    agents: "Ask your shop anything; approve every change",
  },
  more: {
    product: "Explore all eight modules",
    integrations: "All integrations",
    security: "How we protect your data",
    pricing: "See pricing",
  },
  product: {
    title: "One app for the whole cash-on-delivery business.",
    lead: "Eight modules that share one order, one customer and one stock. Nothing is typed twice, and nothing slips between WhatsApp, the courier and your notebook.",
    subnav: "Modules",
    extrasTitle: "And everything a real shop needs around it.",
    extras: [
      ["Team & roles", "Owner, manager, operator, viewer — or exactly the permissions you choose."],
      ["Instant search", "Ctrl K finds any order, customer, product or conversation."],
      ["Import & export", "Bring your Excel, Shopify or YouCan history. Take your data anywhere."],
      ["Daily report", "A summary of the day sent to your phone at the hour you pick."],
      ["Several shops", "Run separate shops from one install, each with its own data."],
      ["Works offline", "Confirm, pack and count money even when the connection drops."],
    ],
  },
  integrations: {
    title: "Plugged into how Algeria sells.",
    lead: "The messaging app your customers use, the couriers you ship with, the stores and sheets your orders come from — connected in minutes, from inside the app.",
    groups: [
      {
        title: "Messaging",
        items: [["WhatsApp", "Link your business number by scanning a QR code. Every chat lands in a shared team inbox, and AI turns messages into orders."]],
      },
      {
        title: "Couriers",
        items: [
          ["Yalidine", "Create shipments, follow every status and compare home and desk prices per wilaya."],
          ["ZR Express", "Shipments and tracking without leaving SahelFlow."],
          ["EcoTrack", "One connection for the couriers that run on EcoTrack."],
          ["Maystro Delivery", "Create and track Maystro shipments from the order itself."],
        ],
      },
      {
        title: "Stores, forms & sheets",
        items: [
          ["Google Sheets", "Orders your landing pages or forms write into a sheet arrive on their own, and each row shows its live SahelFlow status. No Google Cloud setup.", "new"],
          ["Shopify", "New store orders flow into your confirmation queue."],
          ["YouCan", "Your YouCan orders, confirmed and shipped from SahelFlow."],
          ["WooCommerce", "WordPress store orders synced into one queue."],
          ["SahelFlow storefront", "Build your own store in four steps; orders land directly in the app."],
        ],
      },
      {
        title: "Ads & AI",
        items: [
          ["Meta Pixel & Conversions API", "Storefront purchases reported to your Meta campaigns, so ads learn from real orders."],
          ["Google Gemini", "Use your own key — the free tier works — for order extraction and the shop assistant."],
        ],
      },
      {
        title: "Your data",
        items: [["Excel / CSV", "Import orders, products and customers with column matching and a preview. Export whenever you want."]],
      },
    ],
    missing: "Using a courier or a tool that isn't here? Tell us on WhatsApp.",
  },
  pricing: {
    title: "Simple pricing. Pay once, it's yours.",
    lead: "Try everything free for 7 days. Then buy a licence for your PC — one payment, with a year of updates and support included.",
    trial: {
      name: "Free trial",
      price: "0 DA",
      per: "for 7 days",
      points: ["Every module unlocked", "WhatsApp, couriers and AI included", "No card, no commitment", "Your data stays when you buy"],
      cta: "Download and start",
    },
    licence: {
      name: "SahelFlow licence",
      badge: "Most sellers",
      ask: "Price on WhatsApp",
      per: "one-time payment",
      offer: (seats) => `Launch offer · first ${seats} sellers`,
      then: (regular) => `then ${regular}`,
      save: "−50%",
      points: ["Permanent licence for one PC", "12 months of updates and priority support", "1 shop, up to 5 team members", "Every module and every integration", "Pay by BaridiMob or CCP"],
      cta: "Get my licence",
    },
    custom: {
      name: "Bigger business",
      price: "Tailored",
      per: "shops · team · PCs",
      points: ["Several shops", "A larger team", "More than one PC", "Help moving your history in"],
      cta: "Talk to us",
    },
    howTitle: "Buying takes five minutes.",
    how: [
      ["Pay", "BaridiMob or CCP — we confirm on WhatsApp."],
      ["Send your code", "Copy the licence request code from the app and send it to us."],
      ["Activate", "Paste the licence you receive into \"Activate my licence\". Done."],
    ],
    faq: [
      ["What happens after the 12 months?", "Your SahelFlow keeps working with everything you have. Renewing updates and support is optional, whenever you want."],
      ["Do I lose my work when the trial ends?", "No. Everything stays on your PC. Activating a licence reopens it exactly as you left it."],
      ["Can I move to a new PC?", "Yes. Write to us and we transfer your licence; your backup brings your data along."],
      ["Do you accept card payments?", "Today: BaridiMob and CCP. Write to us if you need another way to pay."],
    ],
  },
  security: {
    title: "Your shop's data lives on your PC. Not on ours.",
    lead: "SahelFlow keeps your database on your own computer, encrypts what is sensitive and asks before anything important changes. Here is exactly how.",
    items: [
      ["Local first", "Orders, customers, stock and money are stored on your PC. There is no SahelFlow server holding your shop."],
      ["Encrypted at rest", "Phone numbers, addresses, conversations and keys are encrypted with AES-256-GCM on disk."],
      ["PIN, sessions, roles", "Every person signs in with their own PIN and sees only what their role allows."],
      ["Encrypted backups", "Create backups whenever you want and restore them safely on a new PC."],
      ["AI that asks first", "The assistant proposes; you approve. Nothing it suggests runs without your click."],
      ["Signed updates", "Installers and updates are signed, and the app refuses anything that isn't."],
    ],
    flowsTitle: "What leaves your PC — and only when you use it",
    flows: [
      ["WhatsApp", "messages you send and receive"],
      ["Your couriers", "the shipments you create"],
      ["Google Gemini", "only if you turn AI on and consent"],
      ["Licence service", "activation and the free trial"],
      ["Your storefront", "only what you publish"],
    ],
  },
  pricingTeaser: { title: "Free for 7 days. Then one payment.", text: "No subscription treadmill: a permanent licence for your PC, with a year of updates and support. Launch offer: half price for the first 20 sellers." },
};

const fr = {
  nav: {
    product: "Produit",
    integrations: "Intégrations",
    security: "Sécurité",
    pricing: "Tarifs",
    faq: "FAQ",
    talk: "Nous parler",
    start: "Essai gratuit",
    allFeatures: "Voir toutes les fonctionnalités",
    newBadge: "Nouveau",
    spotlightTitle: "Synchro Google Sheets",
    spotlightText: "Les commandes de la feuille de vos landing pages arrivent seules — et chaque ligne affiche son statut en direct.",
    close: "Fermer le menu",
  },
  modules: {
    orders: "La file de confirmation vous dit qui appeler d'abord",
    inbox: "Tous vos chats WhatsApp dans une boîte d'équipe, commandes extraites par l'IA",
    delivery: "Yalidine, ZR Express, EcoTrack, Maystro — expédiez et suivez",
    risk: "Sachez quelle commande reviendra avant de l'expédier",
    storefront: "Une boutique en quatre étapes, commandes dans SahelFlow",
    automations: "Messages et relances qui tournent pendant que vous dormez",
    accounting: "Ce que le livreur a encaissé, gardé et vous doit",
    agents: "Interrogez votre boutique ; validez chaque changement",
  },
  more: {
    product: "Découvrir les huit modules",
    integrations: "Toutes les intégrations",
    security: "Comment nous protégeons vos données",
    pricing: "Voir les tarifs",
  },
  product: {
    title: "Une seule app pour tout le commerce en paiement à la livraison.",
    lead: "Huit modules qui partagent la même commande, le même client et le même stock. Rien n'est saisi deux fois, rien ne se perd entre WhatsApp, le livreur et votre cahier.",
    subnav: "Modules",
    extrasTitle: "Et tout ce dont une vraie boutique a besoin autour.",
    extras: [
      ["Équipe et rôles", "Propriétaire, manager, opérateur, lecteur — ou exactement les droits que vous choisissez."],
      ["Recherche instantanée", "Ctrl K retrouve n'importe quelle commande, client, produit ou conversation."],
      ["Import et export", "Reprenez votre historique Excel, Shopify ou YouCan. Emportez vos données partout."],
      ["Rapport quotidien", "Le résumé de la journée envoyé sur votre téléphone à l'heure choisie."],
      ["Plusieurs boutiques", "Gérez des boutiques séparées depuis une installation, chacune avec ses données."],
      ["Fonctionne hors ligne", "Confirmez, préparez et comptez l'argent même quand la connexion tombe."],
    ],
  },
  integrations: {
    title: "Branché sur la façon dont l'Algérie vend.",
    lead: "L'application de messagerie de vos clients, les livreurs avec qui vous expédiez, les boutiques et feuilles d'où viennent vos commandes — connectés en quelques minutes, depuis l'app.",
    groups: [
      {
        title: "Messagerie",
        items: [["WhatsApp", "Reliez votre numéro professionnel en scannant un QR code. Chaque chat arrive dans une boîte d'équipe, et l'IA transforme les messages en commandes."]],
      },
      {
        title: "Livreurs",
        items: [
          ["Yalidine", "Créez les expéditions, suivez chaque statut et comparez les prix domicile et bureau par wilaya."],
          ["ZR Express", "Expéditions et suivi sans quitter SahelFlow."],
          ["EcoTrack", "Une seule connexion pour les livreurs qui tournent sur EcoTrack."],
          ["Maystro Delivery", "Créez et suivez vos colis Maystro depuis la commande."],
        ],
      },
      {
        title: "Boutiques, formulaires et feuilles",
        items: [
          ["Google Sheets", "Les commandes que vos landing pages ou formulaires écrivent dans une feuille arrivent seules, et chaque ligne affiche son statut SahelFlow. Sans Google Cloud.", "new"],
          ["Shopify", "Les nouvelles commandes arrivent dans votre file de confirmation."],
          ["YouCan", "Vos commandes YouCan, confirmées et expédiées depuis SahelFlow."],
          ["WooCommerce", "Les commandes de votre boutique WordPress dans une seule file."],
          ["Boutique SahelFlow", "Créez votre boutique en quatre étapes ; les commandes arrivent directement dans l'app."],
        ],
      },
      {
        title: "Publicité et IA",
        items: [
          ["Meta Pixel et API Conversions", "Les achats de la boutique remontent à vos campagnes Meta, pour des pubs qui apprennent des vraies commandes."],
          ["Google Gemini", "Votre propre clé — l'offre gratuite suffit — pour l'extraction des commandes et l'assistant."],
        ],
      },
      {
        title: "Vos données",
        items: [["Excel / CSV", "Importez commandes, produits et clients avec association des colonnes et aperçu. Exportez quand vous voulez."]],
      },
    ],
    missing: "Vous utilisez un livreur ou un outil absent de la liste ? Dites-le-nous sur WhatsApp.",
  },
  pricing: {
    title: "Des tarifs simples. Payez une fois, c'est à vous.",
    lead: "Essayez tout gratuitement pendant 7 jours. Ensuite, achetez une licence pour votre PC — un seul paiement, avec un an de mises à jour et de support inclus.",
    trial: {
      name: "Essai gratuit",
      price: "0 DA",
      per: "pendant 7 jours",
      points: ["Tous les modules débloqués", "WhatsApp, livreurs et IA inclus", "Sans carte, sans engagement", "Vos données restent si vous achetez"],
      cta: "Télécharger et commencer",
    },
    licence: {
      name: "Licence SahelFlow",
      badge: "Le choix des vendeurs",
      ask: "Prix sur WhatsApp",
      per: "paiement unique",
      offer: (seats) => `Offre de lancement · ${seats} premiers vendeurs`,
      then: (regular) => `puis ${regular}`,
      save: "−50 %",
      points: ["Licence permanente pour un PC", "12 mois de mises à jour et support prioritaire", "1 boutique, jusqu'à 5 membres", "Tous les modules et toutes les intégrations", "Paiement BaridiMob ou CCP"],
      cta: "Obtenir ma licence",
    },
    custom: {
      name: "Grande entreprise",
      price: "Sur mesure",
      per: "boutiques · équipe · PC",
      points: ["Plusieurs boutiques", "Une équipe plus grande", "Plus d'un PC", "Aide pour reprendre votre historique"],
      cta: "Nous parler",
    },
    howTitle: "Acheter prend cinq minutes.",
    how: [
      ["Payez", "BaridiMob ou CCP — nous confirmons sur WhatsApp."],
      ["Envoyez votre code", "Copiez le code de demande de licence depuis l'app et envoyez-le-nous."],
      ["Activez", "Collez la licence reçue dans « Activer ma licence ». C'est fait."],
    ],
    faq: [
      ["Que se passe-t-il après les 12 mois ?", "Votre SahelFlow continue de fonctionner avec tout ce que vous avez. Renouveler les mises à jour et le support est facultatif, quand vous voulez."],
      ["Est-ce que je perds mon travail à la fin de l'essai ?", "Non. Tout reste sur votre PC. Activer une licence rouvre tout exactement comme vous l'avez laissé."],
      ["Puis-je changer de PC ?", "Oui. Écrivez-nous et nous transférons votre licence ; votre sauvegarde ramène vos données."],
      ["Acceptez-vous la carte bancaire ?", "Aujourd'hui : BaridiMob et CCP. Écrivez-nous s'il vous faut un autre moyen."],
    ],
  },
  security: {
    title: "Les données de votre boutique vivent sur votre PC. Pas chez nous.",
    lead: "SahelFlow garde votre base sur votre ordinateur, chiffre ce qui est sensible et demande avant tout changement important. Voici exactement comment.",
    items: [
      ["Local d'abord", "Commandes, clients, stock et argent sont stockés sur votre PC. Aucun serveur SahelFlow ne détient votre boutique."],
      ["Chiffré sur le disque", "Téléphones, adresses, conversations et clés sont chiffrés en AES-256-GCM."],
      ["PIN, sessions, rôles", "Chacun se connecte avec son propre PIN et ne voit que ce que son rôle permet."],
      ["Sauvegardes chiffrées", "Créez des sauvegardes quand vous voulez et restaurez-les en sécurité sur un nouveau PC."],
      ["Une IA qui demande d'abord", "L'assistant propose ; vous validez. Rien ne s'exécute sans votre clic."],
      ["Mises à jour signées", "Installateurs et mises à jour sont signés, et l'app refuse tout le reste."],
    ],
    flowsTitle: "Ce qui sort de votre PC — et seulement quand vous l'utilisez",
    flows: [
      ["WhatsApp", "les messages que vous envoyez et recevez"],
      ["Vos livreurs", "les expéditions que vous créez"],
      ["Google Gemini", "uniquement si vous activez l'IA et y consentez"],
      ["Service de licence", "l'activation et l'essai gratuit"],
      ["Votre boutique", "uniquement ce que vous publiez"],
    ],
  },
  pricingTeaser: { title: "Gratuit 7 jours. Puis un seul paiement.", text: "Pas d'abonnement sans fin : une licence permanente pour votre PC, avec un an de mises à jour et de support. Offre de lancement : moitié prix pour les 20 premiers vendeurs." },
};

const ar = {
  nav: {
    product: "المنتج",
    integrations: "التكاملات",
    security: "الأمان",
    pricing: "الأسعار",
    faq: "الأسئلة",
    talk: "تحدّث معنا",
    start: "جرّب مجاناً",
    allFeatures: "شاهد كل المزايا",
    newBadge: "جديد",
    spotlightTitle: "مزامنة Google Sheets",
    spotlightText: "طلبيات ورقة صفحات الهبوط تصل وحدها — وكل سطر يُظهر حالته مباشرة.",
    close: "إغلاق القائمة",
  },
  modules: {
    orders: "طابور تأكيد يخبرك بمن تتصل أولاً",
    inbox: "كل محادثات واتساب في صندوق للفريق، والطلبات يستخرجها الذكاء الاصطناعي",
    delivery: "Yalidine و ZR Express و EcoTrack و Maystro — اشحن وتابع",
    risk: "اعرف أي طلبية سترجع قبل أن تشحنها",
    storefront: "متجر في أربع خطوات، والطلبات تصل إلى SahelFlow",
    automations: "رسائل وتذكيرات تعمل وأنت نائم",
    accounting: "ما حصّلته شركة التوصيل، وما اقتطعته، وما تدين لك به",
    agents: "اسأل متجرك أي شيء، ووافق على كل تغيير",
  },
  more: {
    product: "اكتشف الوحدات الثماني",
    integrations: "كل التكاملات",
    security: "كيف نحمي بياناتك",
    pricing: "شاهد الأسعار",
  },
  product: {
    title: "تطبيق واحد لكل تجارة الدفع عند الاستلام.",
    lead: "ثماني وحدات تتشارك نفس الطلبية، نفس الزبون ونفس المخزون. لا شيء يُكتب مرتين، ولا شيء يضيع بين واتساب وشركة التوصيل ودفترك.",
    subnav: "الوحدات",
    extrasTitle: "وكل ما يحتاجه متجر حقيقي من حولها.",
    extras: [
      ["الفريق والصلاحيات", "مالك، مدير، عامل، مُطّلع — أو الصلاحيات التي تختارها بالضبط."],
      ["بحث فوري", "Ctrl K يجد أي طلبية أو زبون أو منتج أو محادثة."],
      ["استيراد وتصدير", "انقل سجلّك من Excel أو Shopify أو YouCan. وخذ بياناتك أينما شئت."],
      ["تقرير يومي", "ملخّص اليوم يصل إلى هاتفك في الساعة التي تختارها."],
      ["عدة متاجر", "أدِر متاجر منفصلة من تثبيت واحد، لكل منها بياناته."],
      ["يعمل دون إنترنت", "أكّد وجهّز واحسب المال حتى عندما ينقطع الاتصال."],
    ],
  },
  integrations: {
    title: "موصول بالطريقة التي تبيع بها الجزائر.",
    lead: "تطبيق المراسلة الذي يستعمله زبائنك، شركات التوصيل التي تشحن معها، المتاجر والأوراق التي تأتي منها طلبياتك — تُربط في دقائق، من داخل التطبيق.",
    groups: [
      {
        title: "المراسلة",
        items: [["WhatsApp", "اربط رقمك التجاري بمسح رمز QR. كل محادثة تصل إلى صندوق مشترك للفريق، والذكاء الاصطناعي يحوّل الرسائل إلى طلبيات."]],
      },
      {
        title: "شركات التوصيل",
        items: [
          ["Yalidine", "أنشئ الشحنات، تابع كل حالة وقارن أسعار المنزل والمكتب لكل ولاية."],
          ["ZR Express", "الشحن والتتبع دون مغادرة SahelFlow."],
          ["EcoTrack", "ربط واحد لكل شركات التوصيل العاملة على EcoTrack."],
          ["Maystro Delivery", "أنشئ طرود Maystro وتابعها من الطلبية نفسها."],
        ],
      },
      {
        title: "المتاجر والنماذج والأوراق",
        items: [
          ["Google Sheets", "الطلبيات التي تكتبها صفحات الهبوط أو النماذج في ورقة تصل وحدها، وكل سطر يُظهر حالته في SahelFlow. دون Google Cloud.", "new"],
          ["Shopify", "طلبيات المتجر الجديدة تدخل طابور التأكيد مباشرة."],
          ["YouCan", "طلبيات YouCan تُؤكَّد وتُشحن من SahelFlow."],
          ["WooCommerce", "طلبيات متجر WordPress في طابور واحد."],
          ["متجر SahelFlow", "أنشئ متجرك في أربع خطوات؛ الطلبيات تصل مباشرة إلى التطبيق."],
        ],
      },
      {
        title: "الإعلانات والذكاء الاصطناعي",
        items: [
          ["Meta Pixel و Conversions API", "مشتريات المتجر تُرسل إلى حملات Meta، فتتعلم إعلاناتك من طلبيات حقيقية."],
          ["Google Gemini", "استعمل مفتاحك الخاص — المجاني يكفي — لاستخراج الطلبيات والمساعد الذكي."],
        ],
      },
      {
        title: "بياناتك",
        items: [["Excel / CSV", "استورد الطلبيات والمنتجات والزبائن مع مطابقة الأعمدة ومعاينة. وصدّر متى شئت."]],
      },
    ],
    missing: "تستعمل شركة توصيل أو أداة غير موجودة هنا؟ أخبرنا على واتساب.",
  },
  pricing: {
    title: "أسعار بسيطة. ادفع مرة واحدة، والبرنامج لك.",
    lead: "جرّب كل شيء مجاناً لمدة 7 أيام. ثم اشترِ ترخيصاً لحاسوبك — دفعة واحدة، مع سنة من التحديثات والدعم.",
    trial: {
      name: "التجربة المجانية",
      price: "0 دج",
      per: "لمدة 7 أيام",
      points: ["كل الوحدات مفتوحة", "واتساب، شركات التوصيل والذكاء الاصطناعي مشمولة", "دون بطاقة ودون التزام", "بياناتك تبقى عند الشراء"],
      cta: "حمّل وابدأ",
    },
    licence: {
      name: "ترخيص SahelFlow",
      badge: "اختيار التجار",
      ask: "السعر على واتساب",
      per: "دفعة واحدة",
      offer: (seats) => `عرض الإطلاق · لأول ${seats} تاجراً`,
      then: (regular) => `ثم ${regular}`,
      save: "‎−50%",
      points: ["ترخيص دائم لحاسوب واحد", "12 شهراً من التحديثات والدعم ذي الأولوية", "متجر واحد، حتى 5 أعضاء في الفريق", "كل الوحدات وكل التكاملات", "الدفع عبر BaridiMob أو CCP"],
      cta: "احصل على ترخيصي",
    },
    custom: {
      name: "شركة أكبر",
      price: "حسب الطلب",
      per: "متاجر · فريق · حواسيب",
      points: ["عدة متاجر", "فريق أكبر", "أكثر من حاسوب", "مساعدة في نقل سجلّك"],
      cta: "تحدّث معنا",
    },
    howTitle: "الشراء يستغرق خمس دقائق.",
    how: [
      ["ادفع", "عبر BaridiMob أو CCP — ونؤكد لك على واتساب."],
      ["أرسل رمزك", "انسخ رمز طلب الترخيص من التطبيق وأرسله لنا."],
      ["فعّل", "الصق الترخيص الذي يصلك في «تفعيل ترخيصي». انتهى."],
    ],
    faq: [
      ["ماذا يحدث بعد 12 شهراً؟", "يواصل SahelFlow العمل بكل ما لديك. تجديد التحديثات والدعم اختياري، متى شئت."],
      ["هل أفقد عملي عند نهاية التجربة؟", "لا. كل شيء يبقى على حاسوبك، وتفعيل الترخيص يعيد فتحه كما تركته."],
      ["هل يمكنني تغيير الحاسوب؟", "نعم. راسلنا وننقل ترخيصك، ونسختك الاحتياطية تنقل بياناتك."],
      ["هل تقبلون الدفع بالبطاقة؟", "حالياً: BaridiMob و CCP. راسلنا إن احتجت طريقة أخرى."],
    ],
  },
  security: {
    title: "بيانات متجرك تعيش على حاسوبك. لا عندنا.",
    lead: "SahelFlow يحفظ قاعدة بياناتك على حاسوبك، يشفّر ما هو حساس، ويستأذنك قبل أي تغيير مهم. إليك كيف بالضبط.",
    items: [
      ["محلي أولاً", "الطلبيات والزبائن والمخزون والمال محفوظة على حاسوبك. لا يوجد خادم SahelFlow يحتفظ بمتجرك."],
      ["مشفّر على القرص", "أرقام الهواتف والعناوين والمحادثات والمفاتيح مشفّرة بـ AES-256-GCM."],
      ["رمز سري، جلسات، صلاحيات", "كل شخص يدخل برمزه الخاص ولا يرى إلا ما تسمح به صلاحياته."],
      ["نسخ احتياطية مشفّرة", "أنشئ نسخاً احتياطية متى شئت واسترجعها بأمان على حاسوب جديد."],
      ["ذكاء اصطناعي يستأذن أولاً", "المساعد يقترح، وأنت توافق. لا شيء ينفَّذ دون نقرتك."],
      ["تحديثات موقّعة", "المثبّت والتحديثات موقّعة، والتطبيق يرفض كل ما سواها."],
    ],
    flowsTitle: "ما يغادر حاسوبك — وفقط عندما تستعمله",
    flows: [
      ["واتساب", "الرسائل التي ترسلها وتستقبلها"],
      ["شركات التوصيل", "الشحنات التي تنشئها"],
      ["Google Gemini", "فقط إن فعّلت الذكاء الاصطناعي ووافقت"],
      ["خدمة الترخيص", "التفعيل والتجربة المجانية"],
      ["متجرك الإلكتروني", "فقط ما تنشره"],
    ],
  },
  pricingTeaser: { title: "مجاني 7 أيام. ثم دفعة واحدة.", text: "لا اشتراك لا ينتهي: ترخيص دائم لحاسوبك، مع سنة من التحديثات والدعم. عرض الإطلاق: نصف السعر لأول 20 تاجراً." },
};

export const PAGES = { ar, fr, en };
